// src/app/_components/client.tsx
'use client'

import { parseAsInteger, useQueryState } from 'nuqs'

type ClientProps = {
  title: string
}

export function Client({ title }: ClientProps) {
  const [count, setCount] = useQueryState(
    'count',
    parseAsInteger.withDefault(0)
  )
  return (
    <section>
      <h2>{title}</h2>
      <div style={{ display: 'flex', gap: '0.25rem' }}>
        <button style={{ width: '4rem' }} onClick={() => setCount(null)}>
          Clear
        </button>
        <button style={{ width: '4rem' }} onClick={() => setCount(c => c + 1)}>
          {count}
        </button>
      </div>
    </section>
  )
}

// src/vue/client.vue
<script setup lang="ts">
// @ts-check
import { useRouteQuery } from '@vueuse/router';

const count = useRouteQuery('count', '0', {
  transform: Number,
})

function incrementCount() {
  count.value++
}
function clear() {
  count.value = 0 // Shame we can't remove it from the URL here..
}
</script>

<template>
  <section>
    <h2>Vue Router</h2>
    <div style="display: flex; gap: 0.25rem;">
      <button style="width: 4rem;" @click="clear">Clear</button>
      <button style="width: 4rem;" @click="incrementCount">
        {{ count }}
      </button>
    </div>
  </section>
</template>
